esphome:
  name: dwin-test

esp32:
  board: esp32dev
  framework:
    type: esp-idf

logger:
  level: DEBUG

api:

ota:
  platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

external_components:
  - source:
      type: git
      url: https://github.com/sundeepgoel72/esphome-dWIN
      ref: dev
    components: [dwin]
    refresh: 0s

uart:
  id: dwin_uart
  tx_pin: GPIO17
  rx_pin: GPIO16
  baud_rate: 115200

display:
  - platform: dwin
    id: panel
    update_interval: 5s
